version: '3'
services:
  db-master:
    image: mysql:8.0
    container_name: xbqlmz-mysql-master
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=xbqlmz
      - MYSQL_ROOT_HOST=%
    volumes:
      - ./volumes/db-master/data:/var/lib/mysql
      - ./db_master/init:/docker-entrypoint-initdb.d
      - ./db_master/my.cnf:/etc/mysql/my.cnf
    networks:
      - mysql_cluster
    command: ["--init-file=/docker-entrypoint-initdb.d/01-init-master.sql"]

  db-slave:
    image: mysql:8.0
    container_name: xbqlmz-mysql-slave
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=xbqlmz
      - MYSQL_ROOT_HOST=%
    volumes:
      - ./volumes/db-salve/data:/var/lib/mysql
      - ./db_salve/init:/docker-entrypoint-initdb.d
      - ./db_salve/my.cnf:/etc/mysql/my.cnf
    depends_on:
      - db-master
    networks:
      - mysql_cluster


  redis:
    image: redis:6-alpine
    restart: always
    volumes:
      - ./volumes/redis/data:/data
    command: redis-server --requirepass xbqlmz123456
    ports:
      - "6379:6379"

networks:
  mysql_cluster:
    driver: bridge